# Netlify build configuration
[build]
  command = "npm run build" # 執行 build 的指令
  publish = "dist"          # build 後的產出目錄

# Netlify Functions configuration
[functions]
  directory = "netlify/functions"

  # 告訴 Netlify 在建置環境中可以使用這些環境變數
  # 並在安全掃描時忽略它們
  [build.environment]
    # This should be a comma-separated string, not an array.
    SECRETS_SCAN_OMIT_KEYS = "VITE_FIREBASE_API_KEY,VITE_FIREBASE_AUTH_DOMAIN,VITE_FIREBASE_PROJECT_ID,VITE_FIREBASE_STORAGE_BUCKET,VITE_FIREBASE_MESSAGING_SENDER_ID,VITE_FIREBASE_APP_ID"

# Proxy rule to make Firebase Auth handler appear on the same domain.
# This is the key to solving iOS Safari's storage partitioning issue.
# IMPORTANT: This rule must come BEFORE the general SPA redirect rule.
[[redirects]]
  from = "/__/auth/*"
  to = "https://nail-62ea4.firebaseapp.com/__/auth/:splat"
  status = 200

# API rewrite rule for Netlify Functions
# This rule must come BEFORE the general SPA redirect rule.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Redirect rule for Single Page Applications (SPA)
# 這會將所有找不到的路徑都導向 index.html，讓 React Router 接管
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200